<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProgramadeformacionController;
use App\Http\Controllers\AprendicesController;
use App\Http\Controllers\CentroDeFormacionController;
use App\Http\Controllers\TiposdocumentoController;
use App\Http\Controllers\FichaDeCaracterizacionController;
use App\Http\Controllers\EntecomformadoresController;
use App\Http\Controllers\RolesadministrativosController;
use App\Http\Controllers\IntructoresController;
use App\Http\Controllers\RegionalesController;
use App\Http\Controllers\EpsController;

Route::get('/', function () {    return view('welcome');});
//___________________________________________APRENDICES_______________________________________________________________________
Route::resource('aprendices', AprendicesController::class);
//__________________________________________________________________________________________________________________

//________________________________________PROGRAMA_FORMACION_________________________________________________________________________
Route::resource('programa', ProgramadeformacionController::class);
//__________________________________________________________________________________________________________________

//____________________________________CENTRO_FORMACION_____________________________________________________________________________
Route::resource('centrodeformacion', CentroDeFormacionController::class);
//__________________________________________________________________________________________________________________

//____________________________________TIPO_DOCUMENTO_____________________________________________________________________________
Route::get('/tipodocumento', [TiposdocumentoController::class, 'index']);
//__________________________________________________________________________________________________________________

//________________________________________FICHA_CARACTERIZACION_________________________________________________________________________
Route::resource('fichadecaracterizacion', FichaDeCaracterizacionController::class);
//__________________________________________________________________________________________________________________

//_________________________________________ENTE_CONFORMADOR________________________________________________________________________
Route::get('/enteconformador', [EntecomformadoresController::class, 'index']);
//__________________________________________________________________________________________________________________

//________________________________________ROLES_ADMIN__________________________________________________________________________
Route::get('/rolesadmin', [RolesadministrativosController::class, 'index']);
//__________________________________________________________________________________________________________________

//______________________________________INSTRUCTOR______________________________________________________________________
Route::get('/instructores', [IntructoresController::class, 'index']);
//__________________________________________________________________________________________________________________


//___________________________________REGIONALES_______________________________________________________________________
Route::get('/regionales', [RegionalesController::class, 'index']);


//__________________________________________________________________________________________________________________

//__________________________________________EPS_______________________________________________________________________
//__________________________________________EPS_______________________________________________________________________
Route::resource('eps', EpsController::class);

//____________________________________________________________________________________________________________________

//____________________________________________________________________________________________________________________
